events {}
http {
    server {
        listen 8080;
        
        large_client_header_buffers 4 16k;

        location = /token/validation {
            internal;
            proxy_pass http://security:3000/v1/token/validation;
        }

        location /register {
            proxy_pass http://security:3000/v1/user;
        }

        location /token {
            proxy_pass http://security:3000/v1/token;
        }

        location /user {
            auth_request /token/validation;
            proxy_pass http://security:3000/v1/user;
        }

        location /upload {
            auth_request /token/validation;
            proxy_pass http://uploader:3000/v1/upload;
        }

        location /user/(.+) {
            auth_request /token/validation;
            proxy_pass http://minio:9000/images/$1;
        }
    }
}