{
 "title": "Common",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPULA (nodeexporter)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - avg(rate(node_cpu_seconds_total{instance=\"nodeexporter:9100\",mode=\"idle\"}[1m]))",
     "legendFormat": "CPULA"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - avg(rate(node_cpu_seconds_total{instance=\"nodeexporter:9100\",mode=\"idle\"}[1m]))",
     "legendFormat": "CPULA 1m"
    },
    {
     "expr": "100 - avg(rate(node_cpu_seconds_total{instance=\"nodeexporter:9100\",mode=\"idle\"}[5m]))",
     "legendFormat": "CPULA 5m"
    },
    {
     "expr": "100 - avg(rate(node_cpu_seconds_total{instance=\"nodeexporter:9100\",mode=\"idle\"}[15m]))",
     "legendFormat": "CPULA 15m"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "Memory free" },
    { "expr": "node_memory_MemTotal_bytes" }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Storage free",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_avail_bytes)",
     "legendFormat": "Free space"
    }
   ]
  }
 ]
}