---
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
        enabled: true
  tasks:
    - block:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_version }}.x86_64.rpm"
            dest: "./{{ item }}-{{ clickhouse_version }}.rpm"
          with_items: "{{ clickhouse_packages }}"
      rescue:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/clickhouse-common-static-{{ clickhouse_version }}.x86_64.rpm"
            dest: "./clickhouse-common-static-{{ clickhouse_version }}.rpm"
    - name: Install clickhouse packages
      become: true
      ansible.builtin.yum:
        name:
          - clickhouse-common-static-{{ clickhouse_version }}.rpm
          - clickhouse-client-{{ clickhouse_version }}.rpm
          - clickhouse-server-{{ clickhouse_version }}.rpm
      notify: Start clickhouse service
    - name: Flush handlers
      meta: flush_handlers
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0
- name: Install Vector
  hosts: vector
  handlers: 
    - name: Start Vector service
      become: true
      ansible.builtin.service:
        name: vector
        state: restarted
        enabled: true
  tasks:
    - name: Get Vector distrib
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
        dest: "./vector-{{ vector_version }}.tar.gz"
    - name: Create directory for Vector distrib
      file:
        path: ./vector-{{ vector_version }}
        state: directory
    - name: Unarchive Vector distrib
      ansible.builtin.unarchive:
        src: ./vector-{{ vector_version }}.tar.gz
        dest: ./vector-{{ vector_version }}
        remote_src: true
        extra_opts:
        - --strip-components=2
    - name: Copy Vector bin file
      become: true
      ansible.builtin.copy:
        src: ./vector-{{ vector_version }}/bin/vector
        dest: /usr/bin/vector
        remote_src: true
        owner: root
        group: root
        mode: "0755"
    - name: Copy Vector default
      become: true
      ansible.builtin.copy:
        src: ./vector-{{ vector_version }}/etc/systemd/vector.default
        dest: /etc/default/vector
        remote_src: true
        owner: root
        group: root
        mode: "0755"
    - name: Setup Vector service systemd file
      become: true
      ansible.builtin.template:
        src: templates/vector.service.j2
        dest: /usr/lib/systemd/system/vector.service
    - name: Create directory for Vector config
      become: true
      file:
        path: /etc/vector/
        state: directory
    - name: Setup Vector config
      become: true
      ansible.builtin.template:
        src: templates/vector.yml.j2
        dest: /etc/vector/vector.yaml
    - name: Create Vector group
      become: true
      ansible.builtin.group:
        name: vector
        state: present
    - name: Create Vector user
      become: true
      ansible.builtin.user:
        name: vector
        shell: /bin/sh
        groups: vector
        append: yes
    - name: Reload systemd configs
      become: true
      ansible.builtin.systemd_service:
        daemon_reload: true
      notify: Start Vector service
