---
- name: Test module
  hosts: localhost
  tasks:
  - name: Run test file_content
    spasmaaan.yandex_cloud_elk.file_content_changer:
      vars:
        path: /home/leo-jek/test.txt
        content: Test new 
