x-host: &host
  build: 
    context: .
    dockerfile: Dockerfile.centos7
  restart: on-failure
  command: tail -f /dev/null

services:
  clickhouse-01:
    image: centos:centos7
    container_name: clickhouse-01
    <<: [*host]
  vector-01:
    image: centos:centos7
    container_name: vector-01
    <<: [*host]