---
  - src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.13"
    name: clickhouse
  - src: git@github.com:spasmaaan/ansible-role-vector-test.git
    scm: git
    version: "1.0"
    name: vector-role
  - src: git@github.com:spasmaaan/ansible-role-lighthouse-test.git
    scm: git
    version: "1.1"
    name: lighthouse-role
